<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.5 on linux)" generated="20210616 21:21:55.680" rpa="false" schemaversion="2">
<suite id="s1" name="Test" source="/home/radek/Projects/private/playbot/test/robot/test.robot">
<test id="s1-t1" name="Start browser, context and page and close">
<kw name="New Context" library="Playbot">
<msg timestamp="20210616 21:21:56.984" level="FAIL">Initializing library 'Playbot' with arguments [ browser=firefox ] failed: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/radek/Projects/private/playbot/playbot/Playbot.py", line 11, in __init__
    self._start_browser(browser, **kwargs)
  File "/home/radek/Projects/private/playbot/playbot/Playbot.py", line 21, in _start_browser
    self.browser = sync_playwright().start().firefox.launch(**kwargs)
  File "/home/radek/.cache/pypoetry/virtualenvs/playbot-3zs1Hhjd-py3.9/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 75, in start
    return self.__enter__()
  File "/home/radek/.cache/pypoetry/virtualenvs/playbot-3zs1Hhjd-py3.9/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 42, in __enter__
    raise Error(</msg>
<status status="FAIL" starttime="20210616 21:21:56.983" endtime="20210616 21:21:56.984"/>
</kw>
<kw name="New Page" library="Playbot">
<status status="NOT RUN" starttime="20210616 21:21:56.984" endtime="20210616 21:21:56.984"/>
</kw>
<kw name="Close" library="Playbot">
<status status="NOT RUN" starttime="20210616 21:21:56.984" endtime="20210616 21:21:56.984"/>
</kw>
<doc>get it running</doc>
<status status="FAIL" starttime="20210616 21:21:56.982" endtime="20210616 21:21:56.985">Initializing library 'Playbot' with arguments [ browser=firefox ] failed: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/home/radek/Projects/private/playbot/playbot/Playbot.py", line 11, in __init__
    self._start_browser(browser, **kwargs)
  File "/home/radek/Projects/private/playbot/playbot/Playbot.py", line 21, in _start_browser
    self.browser = sync_playwright().start().firefox.launch(**kwargs)
  File "/home/radek/.cache/pypoetry/virtualenvs/playbot-3zs1Hhjd-py3.9/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 75, in start
    return self.__enter__()
  File "/home/radek/.cache/pypoetry/virtualenvs/playbot-3zs1Hhjd-py3.9/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 42, in __enter__
    raise Error(</status>
</test>
<status status="FAIL" starttime="20210616 21:21:55.681" endtime="20210616 21:21:56.987"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
